language: php
php:
  - '5.6'
  - '5.5'
  - '5.4'
install:
  - ./build/ci-install.sh
  - ./build/ci-compile.sh
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls
